### ISSUE TITLE
Ledger 1.4.1 update

### ISSUE THREAD

**Issue by PuL9** [Bertrand256/dash-masternode-tool#13]
![e346b221-42b9-443d-ba72-015d8787edf4](https://user-images.githubusercontent.com/13856642/37557423-b61c6ffa-2a04-11e8-8cd6-38fecc9533db.png)

2018-03-17 16:56:52 INFO |MainThread |main_dlg.py |setupUi |Finished setup of the main dialog.
2018-03-17 16:57:01 INFO |MainThread |main_dlg.py |connectHardwareWallet |Connecting to a hardware wallet device
2018-03-17 16:57:01 ERROR |MainThread |hw_intf_ledgernano.py |process_ledger_exceptions_int |Error while communicating with Ledger hardware wallet.
Traceback (most recent call last):
  File "hw_intf_ledgernano.py", line 19, in process_ledger_exceptions_int
  File "hw_intf_ledgernano.py", line 35, in connect_ledgernano
  File "src\btchip-python\btchip\btchip.py", line 561, in getFirmwareVersion
  File "src\btchip-python\btchip\btchipComm.py", line 113, in exchange
  File "src\btchip-python\btchip\ledgerWrapper.py", line 61, in unwrapResponseAPDU
btchip.btchipException.BTChipException: Exception : Invalid sequence
2018-03-17 16:57:01 INFO |MainThread |main_dlg.py |connectHardwareWallet |Could not connect to a hardware wallet

**Comment by PuL9** [comment]
![e346b221-42b9-443d-ba72-015d8787edf4](https://user-images.githubusercontent.com/13856642/37557417-a5d96fbc-2a04-11e8-9ff9-28986a7e77f8.png)

**Comment by Bertrand256** [comment]
Version 0.9.17 has been verified against Ledger's 1.4.1 firmware and works correctly, at least with the device I have.

Are you running DMT from a compiled exe from GitHub or executing it from the sources?

Did your device work with the app before upgrading Ledger firmware?

**Comment by PuL9** [comment]
I have downloaded DMT from github, this one - DashMasternodeTool_0.9.17.win64.zip
My Nano S did work with DMT before I have updated it to 1.4.1
Now, when I press "Test HW" it says this

![9ab5b10f-3598-40c9-b629-91b7e0398b1c](https://user-images.githubusercontent.com/13856642/37687295-5421d454-2c9b-11e8-8721-1791a9e50162.png)

**Comment by Bertrand256** [comment]
The error comes from the Ledger client library. They recently published a few minor fixes, for which I've prepared a test DMT executable. Let's check if this changes anything. You can download it from my keybase profile: https://keybase.pub/bertrand256/dash-masternode-tool/executables/0.9.17u/DashMasternodeTool_0.9.17u.win64.zip

**Comment by PuL9** [comment]
It works!

**Comment by Bertrand256** [comment]
That's great; thanks for confirmation. 
I'm closing the issue. This change will be included in v0.9.18.
