### ISSUE TITLE
error giving error message for mistyped password

### ISSUE THREAD

**Issue by taw00** [Bertrand256/dash-masternode-tool#24]
*Note on my setup: Fedora Linux 29, x86_64, my builds of your code.*

See attached screenshot. I *think* this happened because I mistyped the password for my Trezor twice. --probably identically-- when trying to transfer some funds. You can't see what you are typing so it is hard to tell.

"UnexpectedMessage: Unknown message"
![incorrect-password-error-message-not](https://user-images.githubusercontent.com/6908872/53354978-06e08b00-38f6-11e9-9200-df3452946000.png)

**Comment by Bertrand256** [comment]
The reason is probably a not supported message type in the python-trezor client library, returned from the device in this scenario.
Can you find the "UnexpectedMessage" string in the log file, copy the error stack accompanying it and post it here?

BTW: I suppose that there would be some benefits if I implemented the possibility of showing the password in this dialog.

**Comment by taw00** [comment]
Hmm. There are a few instances of this popping up in the logs. I *think* this is the right instance.
```
2019-02-25 12:02:21 ERROR|root|MainThread|main_dlg.py|connect_hardware_wallet|Exception while connecting hardware wallet
Traceback (most recent call last):
  File "main_dlg.py", line 735, in connect_hardware_wallet
  File "hw_intf.py", line 196, in connect_hw
  File "hw_intf.py", line 179, in get_session_info_trezor
  File "wnd_utils.py", line 150, in run_thread_dialog
  File "wnd_utils.py", line 138, in call
  File "thread_fun_dlg.py", line 366, in run
  File "hw_intf.py", line 169, in call_get_public_node
  File "trezorlib/tools.py", line 208, in wrapped_f
  File "trezorlib/btc.py", line 36, in get_public_node
  File "trezorlib/tools.py", line 229, in wrapped_f
  File "trezorlib/client.py", line 177, in call
trezorlib.exceptions.TrezorFailure: UnexpectedMessage: Unknown message
```

**Comment by Bertrand256** [comment]
In the current firmware versions the problem seem to be fixed, so I close the issue. Feel free to re-open it if you encounter it anyway.
