### ISSUE TITLE
Ledger Blue : Balance issue with one of my addresses

### ISSUE THREAD

**Issue by qwizzie** [Bertrand256/dash-masternode-tool#65]
One of my Ledger Blue account addresses (a normal wallet account, where my Masternode Payments were sent to) is showing an incorrect balance (10 dash), when i connect my Ledger hardware wallet and press 'wallet'. I can't get it to show the correct balance (0 dash). I ended up hiding that specific account / address within DMT and registered a different Ledger payout address and that is working fine. 

* Below is the dmt log file that at the very end does seem to show a failure to purge a timed-out unconfirmed transaction (td_id: 1885). I copied this DMT log after DMT was finished fetching all transactions.
* Also whenever i connect my Ledger Blue and press 'wallet' it shows a 'ledgerwallet.client.CommException: Exception : Invalid status 6d00 (Unknown reason)' in the DMT log. Could be due to me using Ledger Blue or it could be unrelated, luckily this does not affect DMT usage in any way.

DMT log : 

2024-01-09 18:15:41 INFO|root|MainThread|app_config.py|init|===========================================================================
2024-01-09 18:15:41 INFO|root|MainThread|app_config.py|init|Application started (v 0.9.38)
2024-01-09 18:15:41 INFO|root|MainThread|main_dlg.py|setupUi|Finished setup of the main dialog.
2024-01-09 18:15:44 INFO|dmt.dashd_intf|MainThread|dashd_intf.py|read_masternode_data_from_db|DB read time of 3944 MASTERNODES: 0.29827141761779785 s
2024-01-09 18:15:44 INFO|root|MainThread|app_main_view_wdg.py|refresh_net_masternodes_view|Starting thread "refresh_net_masternodes_view_thread"
2024-01-09 18:15:44 INFO|root|MainThread|app_main_view_wdg.py|refresh_network_data|Starting thread "refresh_status_thread"
2024-01-09 18:15:44 INFO|dmt.dashd_intf|Dummy-2|dashd_intf.py|open_internal|Connecting to: https://suzy.dash-masternode-tool.org:443
2024-01-09 18:15:45 INFO|dmt.dashd_intf|Dummy-1|dashd_intf.py|read_masternode_data_from_db|DB read time of 3944 MASTERNODES: 0.3793458938598633 s
2024-01-09 18:15:45 INFO|dmt.dashd_intf|Dummy-2|dashd_intf.py|get_masternodelist|Fetching protx data from the network
2024-01-09 18:15:45 INFO|root|Dummy-3|main_dlg.py|get_project_config_params_thread|Loaded the project configuration params: {'appCurrentVersion': '0.9.38', 'exeDownloads': {'mac': 'https://github.com/Bertrand256/dash-masternode-tool/releases/download/v0.9.38/DashMasternodeTool_0.9.38.mac.dmg', 'win64': 'https://github.com/Bertrand256/dash-masternode-tool/releases/download/v0.9.38/DashMasternodeTool_0.9.38.win64.zip', 'linux': 'https://github.com/Bertrand256/dash-masternode-tool/releases/download/v0.9.38/DashMasternodeTool_0.9.38.linux.tar.gz'}, 'defaultDashdProtocol': {'mainnet': 70227, 'testnet': 70227}, 'sporks': [{'name': 'SPORK_6_NEW_SIGS', 'active': {'mainnet': False, 'testnet': False}}, {'name': 'SPORK_15_DETERMINISTIC_MNS_ENABLED', 'active': {'mainnet': True, 'testnet': True}}], 'features': {'NON_DETERMINISTIC_MNS': {'mainnet': {'status': 'disabled', 'priority': 4}, 'testnet': {'status': 'disabled', 'priority': 4}}, 'DETERMINISTIC_MNS': {'mainnet': {'status': 'enabled', 'priority': 4}, 'testnet': {'status': 'enabled', 'priority': 4}}, 'REGISTER_DMN_AUTOMATIC': {'mainnet': {'status': 'enabled', 'priority': 4, 'message': ''}, 'testnet': {'status': 'enabled', 'priority': 4, 'message': ''}}, 'UPDATE_REGISTRAR_AUTOMATIC': {'mainnet': {'status': 'enabled', 'priority': 4, 'message': ''}, 'testnet': {'status': 'enabled', 'priority': 4, 'message': ''}}, 'UPDATE_SERVICE_AUTOMATIC': {'mainnet': {'status': 'enabled', 'priority': 4, 'message': ''}, 'testnet': {'status': 'enabled', 'priority': 4, 'message': ''}}, 'REVOKE_OPERATOR_AUTOMATIC': {'mainnet': {'status': 'enabled', 'priority': 4, 'message': ''}, 'testnet': {'status': 'enabled', 'priority': 4, 'message': ''}}, 'NEW_BLS_SCHEME': {'mainnet': {'status': 'enabled', 'priority': 4, 'message': ''}, 'testnet': {'status': 'enabled', 'priority': 4, 'message': ''}}}, 'params': {'voteTimeRandomOffsetMin': -720, 'voteTimeRandomOffsetMax': 60}, 'appDeveloperContact': [{'name': '674141414141426b644c38446f4a7a77494a7a6632393751396d576d687531375575344a69515f373056335a494d34784f34564d3770614b55592d4e557a6c4d38616f524f496254564b785a496f62514256496159436b55797359524d5375456b773d3d', 'userId': '674141414141426b644c7a57306f4e693154494e336e4b45666979426c4a724c556e6f69395547416d45346c4971305853782d324d75624b46644662545042665275317a4a72645a73655939577648746f43616f394c79306f576a337a6235756b673d3d', 'url': '674141414141426b644c386f593872655172747876726238485663567679776b434547625a576e4e426f686c56684a4d756a6e35476377364b61387858696b56576e66465148666b5a5338764176387673665f50394f56564c39764a346c7335626372596b346244324f5a497175476d4b62484f656a35584a4d4a6469717438646249646f654c304b7436786d5a736d384941556470644b5252314e5479673673773d3d'}, {'name': '674141414141426b644c37537476463742304a51304b772d655544586e64373671704e633274324977597465756c334c35302d57623857645a696849317a566d4f4b5f53786871487577465541733157354f365334793438634d49585f624f3544773d3d', 'userId': '674141414141426b644c7a6a716556594858304f696657614536566d712d4f32424a4b58646c347745766562646951725246534f7172556a452d784e4465516a62374d322d78766e5f73703347705a526472637377772d764b6d6931765a487850413d3d', 'url': '674141414141426b644c376d4856432d6e41534967457472667561596b6957492d6951744633366a2d456437735074326862434a777156677a6c64736d7251744757546a385a694c6a63557378523255594e494632466b667651742d584258516271377a5161594264414f734d5366574678716a7845644e2d63544368486d4e72676e5159365756672d736535444154756c34426839534e505a726d5f4c583972513d3d'}, {'name': '674141414141426b644c38363252767a3657444e674e474448636b435a7a32494b307478614c4e434c6a50704f795a5f532d747a6d6e76496a3377554a48756d44577a5745584d6f5934414262515462735835465a7074505f6a704f4441753139773d3d', 'userId': '674141414141426b644c7a423258326c597833614359594b6851553179774251386a4b56796e654365643930595f4149396f615932546c6f475a31744a4779786d7168456a782d432d36706c6474616737507177527367706c5057537a746135466d656331534a4541682d7739476f5f4147537147766b3d', 'url': '674141414141426b644c397777576846764e5048624f39574b4a55733049542d697069733973775a7a386c506654596759422d4c515269586f544876686f36434e4a765130376d38585453615932424e74706d66366c49554b55486b6e5041715349374d386c55644e33786f4c4d345f5f70744166782d5833764e787058716d7037436c76755f416d45335437774232456a48784a3242646e382d784d4c5548645f5466334e49776b64794350754264543952654a34303d'}, {'name': '674141414141426b644c3643516b334d5a453777303169734b743171325274425a4c48425572663234674157744e547850445a6252354b716c533764642d656451524e35416f50364f436f31717341646e4566484f487a5953686d493357426a62773d3d', 'userId': '674141414141426b644c614a716e77782d4d48327461474b6b724536466e616832527155526669653134756b30686745626e41564f724d4b3451567170575a56565333585f73774b435876666b576a644d537368635f625549334e49675944492d597a3955664e33596b61316a7832796b56554e5970553d', 'url': '674141414141426b644c36577a4a743041394c4f7959434a516e6b626e74665f4463756c444e364e445938766d5a6e364a6671537358414d627146545657445f47756d324f6139596f425f516275694f5442624e76616d6c4774574a5943506d3530595557674a31374e4148394356356e65415744644d3d'}, {'name': '674141414141426b644c366e5f39426855663473425a6b75706a6a59455942774444796e73505a595f7455494e616e5a4c6e4e754f46532d76362d5041414466566f516b356f50497665445269334e57596d42483136486773645a78374a5a6962673d3d', 'userId': '674141414141426b644c68465975664d5471666b5f354c627a4d774d4a5338326175756b6d354f4c74633351354a387761696e6844337947492d6371672d376a5a44456c472d5f7a7335656d386e2d723841436f6e655356354559694f56644371665473706748562d2d767a47316b525f74596d35505168376d48574147743972536a6a4854517367442d4f7a4e6a55714b37703632544753624c49495f4c694267375a52766754797338477847564e494b34385a7a413d', 'url': '674141414141426b644c362d5a34537347523635776a79517339346f524e3957434d53744a56334d6553496c35396d5538686a534355517262644b5f613336524734547a3652676e4863446e6651743079397a6a365671436556735a78396154724b6945555072524f2d59454c785234627a65316158493d'}]}
2024-01-09 18:15:45 INFO|root|Dummy-1|app_main_view_wdg.py|refresh_net_masternodes_view_thread|Masternodes read time from db: 0.38s
2024-01-09 18:15:45 INFO|root|MainThread|app_main_view_wdg.py|update_on_thread_finish|Finished thread "refresh_net_masternodes_view_thread"
2024-01-09 18:15:45 INFO|root|MainThread|app_main_view_wdg.py|apply_net_masternodes_filter|Network masternode filer time: 0.01s
2024-01-09 18:15:45 INFO|root|MainThread|app_main_view_wdg.py|update_on_thread_finish|Masternodes UI refresh time: 0.17s
2024-01-09 18:15:46 INFO|dmt.dashd_intf|Dummy-2|dashd_intf.py|get_masternodelist|Finished fetching protx data from the network
2024-01-09 18:15:46 INFO|dmt.dashd_intf|Dummy-2|dashd_intf.py|get_masternodelist|Fetching masternode data from the network
2024-01-09 18:15:46 INFO|dmt.dashd_intf|Dummy-2|dashd_intf.py|get_masternodelist|Finished fetching masternode data from the network
2024-01-09 18:15:46 INFO|dmt.dashd_intf|Dummy-2|dashd_intf.py|get_masternodelist|Finished processing masternode data
2024-01-09 18:15:47 INFO|dmt.main|Dummy-2|app_main_view_wdg.py|refresh_status_thread|fetch_mempool_txes start
2024-01-09 18:15:53 INFO|dmt.main|Dummy-2|app_main_view_wdg.py|refresh_status_thread|fetch_mempool_txes finish
2024-01-09 18:15:53 INFO|dmt.main|Dummy-2|app_main_view_wdg.py|refresh_status_thread|get address balances start
2024-01-09 18:15:53 INFO|dmt.main|Dummy-2|app_main_view_wdg.py|refresh_status_thread|get address balances finish
2024-01-09 18:15:53 INFO|root|MainThread|app_main_view_wdg.py|refresh_net_masternodes_view|Starting thread "refresh_net_masternodes_view_thread"
2024-01-09 18:15:53 INFO|dmt.dashd_intf|Dummy-4|dashd_intf.py|read_masternode_data_from_db|DB read time of 3944 MASTERNODES: 0.21219277381896973 s
2024-01-09 18:15:53 INFO|root|Dummy-4|app_main_view_wdg.py|refresh_net_masternodes_view_thread|Masternodes read time from db: 0.22s
2024-01-09 18:15:53 INFO|root|MainThread|app_main_view_wdg.py|update_on_thread_finish|Finished thread "refresh_net_masternodes_view_thread"
2024-01-09 18:15:53 INFO|root|MainThread|app_main_view_wdg.py|apply_net_masternodes_filter|Network masternode filer time: 0.01s
2024-01-09 18:15:53 INFO|root|MainThread|app_main_view_wdg.py|update_on_thread_finish|Masternodes UI refresh time: 0.02s
2024-01-09 18:16:08 ERROR|root|MainThread|hw_intf_ledgernano.py|get_device_list|Exception : Invalid status 6d00 (Unknown reason)
Traceback (most recent call last):
  File "hw_intf_ledgernano.py", line 199, in get_device_list
  File "ledgerwallet\client.py", line 420, in get_version_info
  File "ledgerwallet\client.py", line 216, in apdu_exchange
ledgerwallet.client.CommException: Exception : Invalid status 6d00 (Unknown reason)
2024-01-09 18:16:08 INFO|root|MainThread|hw_intf_ledgernano.py|open_session|Ledger Nano connected. Firmware version: 1.4.7, specialVersion: 48, compressedKeys: False
2024-01-09 18:16:23 INFO|dmt.bip44_wallet|Dummy-5|bip44_wallet.py|purge_transaction|Purging timed-out unconfirmed transaction (td_id: 1885).
2024-01-09 18:16:32 WARNING|dmt.bip44_wallet|Dummy-5|bip44_wallet.py|_process_addresses_txs|Balance of address 109 inconsistency. Trying to refetch transactions.

**Comment by qwizzie** [comment]
I decided to delete the cache folder inside the Application Data Folder and that fixed DMT to then show the correct balance again on my Ledger account / address that it previously showed incorrectly. I will keep this methode of deleting the cache folder in mind if i ever have similar problems with DMT in the future.

Let me know if there is something you can do / investigate with the log above or if we should consider this issue as solved......

**Comment by Bertrand256** [comment]
Ledger Blue probably has a slightly changed protocol for communicating with the computer, but I do not have a physical device, verify this. For this reason, DMT officially supports only Ledger Nano S and Nano X devices, but not Blue.

**Comment by qwizzie** [comment]
Okay, no problem. I will close this issue.
